### ISSUE TITLE
How long it takes to load a 500MB dump file?

### ISSUE THREAD

**Issue by quicoli** [drewnoakes/string-theory#15]
Hello,

I'm trying to load a 500MB dump file, it has passed 15 minutes and nothing yet... I'll keep it running here if something changes I'll let you know.

**Comment by quicoli** [comment]
After 1 hour I couldn't see the dump file loaded. Is this a bug?

**Comment by drewnoakes** [comment]
@quicoli it should not take that long. I suspect there was an error and the UI wasn't updated. If that's the case it's a bug I'd like to fix. Is there any way you can share the dump file with me? Be aware there may be sensitive information in the dump file.

If you can't share the dump, perhaps you can run StringTheory in a debugger and break on all exceptions.

**Comment by quicoli** [comment]
@drewnoakes  I'll run in a debugger and let you know

**Comment by quicoli** [comment]
@drewnoakes figure it out. 

When I build the app as Any CPU or Win32  and try to load the dump file, I get the following exception

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Mismatched architecture between this process and the dac.
  Source=Microsoft.Diagnostics.Runtime
  StackTrace:
   at Microsoft.Diagnostics.Runtime.DataTarget.CreateRuntime(ClrInfo clrInfo) in D:\repos\string-theory\clrmd\src\Microsoft.Diagnostics.Runtime\src\DataTargets\DataTarget.cs:line 271
   at Microsoft.Diagnostics.Runtime.ClrInfo.CreateRuntime() in D:\repos\string-theory\clrmd\src\Microsoft.Diagnostics.Runtime\src\DataTargets\ClrInfo.cs:line 96
   at StringTheory.Analysis.HeapAnalyzer..ctor(DataTarget dataTarget) in C:\Dev\string-theory-master\StringTheory\Analysis\HeapAnalyzer.cs:line 34
   at StringTheory.Analysis.HeapAnalyzer..ctor(String dumpFilePath) in C:\Dev\string-theory-master\StringTheory\Analysis\HeapAnalyzer.cs:line 16
   at StringTheory.UI.HomePage.<>c__DisplayClass19_1.<.ctor>b__4(CancellationToken token) in C:\Dev\string-theory-master\StringTheory\UI\HomePage.cs:line 52
   at StringTheory.UI.LoadingOperation.<>c__DisplayClass5_0.<.ctor>b__0() in C:\Dev\string-theory-master\StringTheory\UI\LoadingOperation.cs:line 23
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

But if I build it as x64, the dump file is loaded correctly.

**Comment by quicoli** [comment]
I know this isn't the right place for discussion of results.... looks like XAML needs some optimization....

![image](https://user-images.githubusercontent.com/8388239/52562334-1c35bf80-2df6-11e9-9c41-99849928848c.png)

**Comment by quicoli** [comment]
looks like WPF needs some optimization ???
![image](https://user-images.githubusercontent.com/8388239/52562444-73d42b00-2df6-11e9-9e8f-0d04ea8acab2.png)

**Comment by quicoli** [comment]
Looks like WPF needs some optimization...

![image](https://user-images.githubusercontent.com/8388239/52562516-a3833300-2df6-11e9-8aac-008cfff5bbfe.png)

**Comment by drewnoakes** [comment]
Glad you got it working.

@AndreasHassing fixed the issue that was swallowing the exception in #17. See #11 for issues around mismatched architectures.

I'll close this for now. Let me know if there's anything else.
